### ISSUE TITLE
localhost deploy issue

### ISSUE THREAD

**Issue by bxlkm** [lidofinance/lido-dao#448]
========================================
DAO template
========================================
DAO template name: template.lidopm.eth (0x85edf5bebfa6a88b4177e01c7d36ea6642f831cab402e7dc52133a951b3ba1e1)
Using Lido APM registry: undefined
Error: Invalid address passed to APMRegistry.at(): undefined
    at Function.at (/Users/likunmiao/lido-project/lido-dao/node_modules/@nomiclabs/truffle-contract/lib/contract/constructorMethods.js:67:13)
    at deployDaoTemplate (/Users/likunmiao/lido-project/lido-dao/scripts/deploy-lido-apm-and-template.js:123:66)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at deployApmAndTemplate (/Users/likunmiao/lido-project/lido-dao/scripts/deploy-lido-apm-and-template.js:79:30)

**Comment by bxlkm** [comment]
resolved
