### ISSUE TITLE
Error when deploy lido apm on goerli

### ISSUE THREAD

**Issue by daxionga** [lidofinance/lido-dao#455]
I follow the [doc](https://docs.lido.fi/guides/multisig-deployment/) to depley the contract in the goerli network,and only modify the contract address as follow 
```json
{
  "networkId": 5,
  "ensAddress": "0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e",
  "daoFactoryAddress": "0x0B6769F500b293e3adacD97c3961189565069902",
  "apmRegistryFactoryAddress": "0x70B3284fD016a570146cE48fC54D7A81bCd94BBa",
  "miniMeTokenFactoryAddress": "0x92E2750729e04c9a5CF21A830Bd00cbd5139D992",
  "aragonIDAddress": "0x673cB86B60B9768Eebb05517fbF5a7F9f1Ab62C4",
  "multisigAddress": "0x552224DCf7b0A0A8C691b1013Fe8488d46BfA5FB"
}
```
It was ok when deploy the contract  with the [doc](https://docs.lido.fi/guides/multisig-deployment/) 1/2/3/4 but when I deploy the apm for step 5 It return a error when run 
```sh
 yarn hardhat --network mainnet run ./scripts/multisig/05-deploy-apm.js
```
the error log
```
========================================
Network ID: 5
Reading network state from /Users/oker/Documents/lido-dao/deployed-goerli.json...
====================
APM ENS domain: lidookpopopm.eth
Using DAO template: 0x9A50dCD54065AD99E1568582BFbf1ae743aDa095
Using LidoTemplate deploy block: 8003642
====================
✓ LidoTemplate has generated no events
✓ ENS node is owned by the DAO template
====================
Parent domain: eth 0x93cdeb708b7545dc668eb9280176169d1c33cfd8ed6f04690a0bcc88a93fc4ae
Subdomain label: lidookpopopm 0x3f5b2bf0c0bf035ee4824fd073862262f53e26c808743494b7d83b98bf21eafc
====================
Error: Returned error: execution reverted
    at Object.ErrorResponse (/Users/oker/Documents/lido-dao/node_modules/web3-core-helpers/src/errors.js:29:16)
    at /Users/oker/Documents/lido-dao/node_modules/@truffle/interface-adapter/node_modules/web3-core-requestmanager/src/index.js:140:36
    at cb (util.js:207:31)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```
It was found that the exception thrown by this code
```js
async function getTxData(txObj, opts = {}) {
  const gas = await txObj.estimateGas({
    ...opts,
    from: opts.from || (await web3.eth.getAccounts())[0]
  })
  return {
    ...opts,
    gas: gas + 10000,
    data: txObj.encodeABI()
  }
}
````

I don‘t know how to reslove it,anyone know that?

**Comment by TheDZhon** [comment]
Please see https://github.com/lidofinance/lido-dao/issues/461#issuecomment-1475360669
